import { Raleway, Inter,Montserrat} from "next/font/google";
import "./globals.css";
import SidebarMenu from "./Components/SidebarMenu";
import Navbar from "./Components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const raleway = Raleway({ subsets: ["latin"] });
const inter = Inter({ subsets: ["latin"] });
const montserrat = Montserrat({ subsets: ["latin"] });
// const poppins = Poppins({ subsets: ["latin"] });


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <div className="flex">
         <SidebarMenu />
         <div className="ml-[18%] w-[82vw] flex flex-col">
         <Navbar/>
         {children}
         </div>
        </div>
        
        </body>
    </html>
  );
}
