import {Montserrat} from "next/font/google";
import "./globals.css";
import SidebarMenu from "./components/SidebarMenu";
import Navbar from "./components/Navbar";
import { SessionProvider } from "next-auth/react"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const montserrat = Montserrat({ subsets: ["latin"] });
// const poppins = Poppins({ subsets: ["latin"] });


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <SessionProvider>
          <div className="flex">
           <SidebarMenu />
           <div className="ml-[18%] w-[82vw] flex flex-col">
           <Navbar/>
           {children}
           </div>
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}
