import { Raleway, Inter, Poppins } from "next/font/google";
import "./globals.css";
import SidebarMenu from "./Components/SidebarMenu";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const raleway = Raleway({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <div className="flex">
         <SidebarMenu />
        {children}
        </div>
        
        </body>
    </html>
  );
}
