import { z } from 'zod';

const productSchema = z.object({
  productName: z.string().min(3, 'Product Name is required and should be at least 3 characters long'),
  category: z.string().min(3, 'Category is required and should be at least 3 characters long'),
  subCategory: z.string().min(3, 'Sub-Category is required and should be at least 3 characters long'),
  sku: z.string().min(5, 'SKU is required and should be at least 5 characters long'),
  description: z.string().min(6, 'Description is required and should be at least 6 characters long'),
  goldKarat: z.string().optional(),
  goldWeight: z.string().optional(),
  diamondCarat: z.string().optional(),
  diamondQuality: z.string().optional(),
  numberOfDiamonds: z.string().transform((value) => Number(value)).default(0).optional(),
  metalType: z.string().optional(),
  height: z.string().transform((value) => Number(value)).default(0).optional(),
  width: z.string().transform((value) => Number(value)).default(0).optional(),
  costPrice: z.string().transform((value) => Number(value)).pipe(z.number().min(1, 'Cost Price is required and should be greater than 0')),
  sellingPrice: z.string().transform((value) => Number(value)).pipe(z.number().min(1, 'Selling Price is required and should be greater than 0')),
  makingCharges: z.string().transform((value) => Number(value)).default(0).optional(),
  discount: z.string().transform((value) => Number(value)).default(0).optional(),
  quantityAvailable: z.string().transform((value) => Number(value)).default(1),
  taxDetails: z.string().optional(),
  availabilityStatus: z.string().default("In Stock"),
  certificationDetails: z.string().optional(),
  warranty: z.string().optional(),
  returnPolicy: z.string().min(20, 'Return Policy is required and should be at least 20 characters long'),
  productCollection: z.string().default("New Arrivals"),
  gender: z.string().min(3, 'Gender is required'),

  // supplierName: z.string().optional(),
  // manufacturerDetails: z.string().optional(),
  // countryOfOrigin: z.string().optional(),
  // seoTitle: z.string().optional(),
  // metaDescription: z.string().optional(),
  // keywords: z.array(z.string()).optional(),
  // tags: z.array(z.string()).optional(),
  // shippingWeight: z.string().optional(),
  // shippingClass: z.string().optional(),
  // leadTime: z.string().optional(),
  // shippingCharges: z.string().optional(),
  // specialInstructions: z.string().optional(),
  // notes: z.string().optional(),
});

export default productSchema;